const phrases = {
  titles: {
    categories: "Категории",
    add: "Добавление новой категории",
    edit: "Редактирование категории",
    products: "Товары",
    productAdd: "Добавление товара",
    productEdit: "Редактирование товара",
    slides: "Слайды",
    slideAdd: "Добавление слайда",
    slideEdit: "Редактирование слайда",
  },
  buttons: {
    add: "Добавить",
    cancel: "Отмена",
    remove: "Удалить",
    save: "Сохранить",
    download: "Загрузить",
  },
  common: {
    parentCategory: "Главная",
  },
  available: ["Нету", "Мало", "Достаточно", "Много"],
  fields: {
    category: {
      name: "Название",
      sort: "Сортировка",
      description: "Описание",
      link: "Ссылка",
      active: "Категория включена",
      parent: "Родительская категория",
      image: "Ссылка на изображение",
    },
    slide: {
      name: "Заголовок слайда",
      sort: "Сортировка",
      description: "Текст под заголовком",
      link: "Ссылка для перехода",
      active: "Показывать ли слайд",
      image1: "Изображение слева",
      image2: "Изображение справа",
    },
    product: {
      name: "Название",
      sort: "Сортировка",
      description: "Краткое описание",
      link: "Ссылка",
      top: "Выводить в ТОП товаров",
      available: "Наличие товара",
      parent: "Родительская категория",
      green: "Зеленый лейбл",
      yellow: "Желтый лейбл",
      price: "Цена поставщика, $",
      addPercent: "Наценка, %",
      discount: "Скидка, %",
      stars: "Оценка, 1-5",
      imageLink: "Вставьте ссылку на изображение",
      images: "Изображения",
      imageSort: "Сортировка",
      imageSrc: "Путь к изображению",
      prices: "Цены и наличие",
      general: "Основная информация",
      labels: "Оценка и подписи",
      props: "Характеристики",
      propSort: "Сортировка",
      propName: "Свойство",
      propValue: "Значение",
      linkAli: "Ссылка в AliExpress",
      getFromAli: "Подгрузить данные из AliExpress",
      priceOnSite: "Цена на сайте: ",
      seo: "Мета-теги (СЕО)",
      seoDescription: "Мета описание",
      seoTitle: "Мета заголовок",
      seoKeywords: "Мета ключевые слова",
    },
  },
};

export default phrases;
